TESTING = True
DEBUG = True
FLASK_ENV = 'chulo'
SECRET_KEY = 'GDtfDCFYjD'
IMAGE_UPLOADS = "C:/puntofacil/"
IMAGE_CODE = "C:/Users/ehidalgo/Dropbox/codigo fuente/app-facil-pos/public/uploads/"
DOCUMENTOS = "C:/Users/ehidalgo/Dropbox/codigo fuente/app-facil-pos/public/uploads/"
CONEXION_SERVIDOR = 'localhost'
CONEXION_USUARIO = "root"
CONEXION_PASSWORD ="Carrizal5755"
CONEXION_BD = "pruebas"
CONEXION_PUERTO = 3306
URL_ACTIVACION = "http://app.tupuntofacil.cl/acticion/"
URL_CAMBIO_PASSWORD = "http://localhost.cl/password/actualizar"
BOLETA_ID = 1
FACTURA_ID = 2
URL_IMAGEN_DEFECTO = "/imgs/defecto.png"
URL_RUTA_IMAGENES = "http://192.168.0.4:5000/imagen/"
URL_RUTA_IMAGENES_PRODUCTOS = "http://localhost:5000/imagen/producto/"
URL_RUTA_IMAGENES_CATEGORIA = "http://localhost:5000/imagen/categoria/"
URL_RUTA_DTE = "http://dte.fpos.cl"
RUTA_DTE =  "C:/configdte/"
RUTA_BASE_IMAGENES = "C:/puntofacil/"
RUTA_IMAGEN_DEFECTO = "C:/puntofacil/defecto.png"
#URL_API_BOLETA= "http://dte.fpos.cl/boletas/recepciona"
URL_API_BOLETA= "http://localhost:8090/talca/boletas/recepciona"
URL_API_COMPROBANTE = "http://localhost:44325/comprobante"
TOKEN_API_DTE = "3545345#EEERTERTERTERTERT__o.ERTRET11232169666"
IVA = 19
#parametros email
PARAMETROS_EMAIL = ["mail.ventagix.cl", 587,"info@ventagix.cl", ""]
